import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('../', import.meta.url));
const assets = JSON.parse(await readFile(path.join(root, 'catalog/assets.manifest.json'), 'utf8')).filter(asset => !['original-glyph', 'original-preview'].includes(asset.kind));
assets.push(...JSON.parse(await readFile(path.join(root, 'catalog/previews.manifest.json'), 'utf8')));
for (const name of ['form', 'system', 'make']) {
  const file = `assets/original/${name}.svg`; const bytes = await readFile(path.join(root, file));
  assets.push({ materialId: 'identity-glyphs', kind: 'original-glyph', name, path: file, bytes: bytes.length, sha256: createHash('sha256').update(bytes).digest('hex'), revision: 'uiux-original-v1', license: 'Project-original specimen; no distribution license assigned', retrievedAt: '2026-10-07' });
}
await writeFile(path.join(root, 'catalog/assets.manifest.json'), JSON.stringify(assets, null, 2) + '\n');
const base = { role: 'uiux-designer', reviewState: 'proposal-only', publicationApproval: false, createdAt: '2026-10-07' };
const materials = [];
function add(id, name, category, recommendation, description, proposal, demo, sourceFiles, extra = {}) {
  const files = assets.filter(asset => asset.materialId === id);
  const asset = files.find(file => file.kind !== 'license');
  const thumbnail = files.find(file => file.kind === 'original-preview')?.path;
  materials.push({ ...base, id, name, category, recommendation, description, proposal, demo, sourceFiles, ...(thumbnail ? { thumbnail } : {}), license: asset?.license ?? 'Project-original specimen; no distribution license assigned', origin: asset?.repo ? 'External licensed asset' : 'Original local specimen', sources: asset?.repo ? [{ title: asset.repo, url: `https://github.com/${asset.repo}/tree/${asset.revision}`, revision: asset.revision }] : [], assets: files.filter(file => file.kind !== 'license').map(file => file.path), notices: files.filter(file => file.kind === 'license').map(file => file.path), fallback: 'Readable static specimen and ordinary controls.', reducedMotion: 'No automatic motion. Explicit playback becomes a static final state when reduced motion is requested.', integration: 'Candidate only. A later owner decision is required before copying it into production.', ...extra });
}
add('font-plex-sans', 'IBM Plex Sans', 'Typography', 'preferred', 'Humanist grotesk with a clear technical voice. Variable width and weight in the supplied font.', '優先提案：正文、案例標題與控制介面使用同一字體，讓工程感保持清楚而不冷硬。', 'font', [], { family: 'IBM Plex Sans', cssFamily: 'Plex Sans', dependency: 'Local TTF; CSS @font-face', parameters: ['Text', 'Size', 'Weight'], tradeoff: 'Its distinctive shapes carry more character than a neutral system sans; test long case-study passages.' });
add('font-inter', 'Inter', 'Typography', 'alternative', 'Neutral variable sans-serif for continuous reading and interface labels.', '備選：若希望讓作品與空間影像承擔更多性格，Inter 可降低字體的存在感。', 'font', [], { family: 'Inter', cssFamily: 'Inter', dependency: 'Local TTF; CSS @font-face', parameters: ['Text', 'Size', 'Weight'], tradeoff: 'Familiar and readable, but less distinctive for the anthology identity.' });
add('font-space-grotesk', 'Space Grotesk', 'Typography', 'accent', 'A geometric display option for short chapter openings and compact titles.', '標題選項：只用於篇章開頭及短標題，長文仍搭配清楚的正文系統。', 'font', [], { family: 'Space Grotesk', cssFamily: 'Space Grotesk', dependency: 'Local TTF; CSS @font-face', parameters: ['Text', 'Size', 'Weight'], tradeoff: 'More expressive at large sizes; avoid using its personality for every small UI label.' });
add('font-plex-mono', 'IBM Plex Mono', 'Typography', 'preferred', 'A regular-weight mono face for dimensions, identifiers and measured information.', '優先提案：與 Plex Sans 配對；技術標籤、參數與代碼使用等寬字，正文保留比例字。', 'font', [], { family: 'IBM Plex Mono', cssFamily: 'Plex Mono', fixedWeight: true, dependency: 'Local regular TTF; CSS @font-face', parameters: ['Text', 'Size'], tradeoff: 'Only the regular face is included in this specimen. Do not synthesize bold as a supplied font weight.' });
add('font-jetbrains-mono', 'JetBrains Mono', 'Typography', 'alternative', 'A variable mono option for code excerpts and a secondary command language.', '備選：適合少量指令及程式片段；不把整個網站做成終端機。', 'font', [], { family: 'JetBrains Mono', cssFamily: 'JetBrains Mono', dependency: 'Local variable TTF; CSS @font-face', parameters: ['Text', 'Size', 'Weight'], tradeoff: 'Its coding association is strong. Use only where it improves the reading of technical information.' });
add('icons-lucide', 'Lucide / outline', 'Icons', 'preferred', 'Twelve actual SVGs for navigation, scene representation and playback controls.', '優先提案：線條節制、圖示命名清楚，適合低干擾的導覽與檢視控制。', 'icons', [], { dependency: 'Local SVG; no icon package required', parameters: ['Size', 'Icon selection'], tradeoff: 'Use icons with text labels. The icon set is for controls, not a substitute for an original identity.' });
add('icons-phosphor', 'Phosphor / regular', 'Icons', 'alternative', 'The same functional control roles expressed through a regular Phosphor selection.', '備選：較有圖形份量，適合需要明顯控制識別的實驗頁。', 'icons', [], { dependency: 'Local SVG; no icon package required', parameters: ['Size', 'Icon selection'], tradeoff: 'The broader silhouettes need careful comparison at small sizes.' });
add('icons-tabler', 'Tabler / outline', 'Icons', 'alternative', 'Twelve outline SVGs, including axis and stacked-layer language.', '備選：工程語彙較多；先保持一套主要 icon，避免把三套混在同一導覽。', 'icons', [], { dependency: 'Local SVG; no icon package required', parameters: ['Size', 'Icon selection'], tradeoff: 'Useful technical range, but a single family should own the eventual interface.' });
add('identity-glyphs', 'FORM / SYSTEM / MAKE', 'Identity', 'preferred', 'Three original geometric marks paired with readable labels.', '身份提案：圓弧與剖線代表 FORM、連接節點代表 SYSTEM、配合面代表 MAKE；不借用影集符號。', 'glyphs', ['src/specimens/assets.js'], { assets: ['assets/original/form.svg', 'assets/original/system.svg', 'assets/original/make.svg'], dependency: 'Original SVG', parameters: ['Size'], tradeoff: 'These are thematic categories, not proficiency ratings. Review the vocabulary before adopting the marks.' });
add('identity-palette', 'Graphite / paper / orange', 'Identity', 'preferred', 'The supplied palette interpreted as surfaces, readable text and one controlled interaction accent.', '色彩提案：橘色主要用於互動與焦點；空間物件的材質仍以中性色呈現。', 'palette', ['src/specimens/assets.js'], { dependency: 'CSS custom properties', parameters: ['Surface context'], tradeoff: 'Thin decorative rules need not be as bright as controls. Contrast is calculated per displayed pairing.' });
add('ui-focus-rail', 'Navigation focus rail', 'Interface', 'preferred', 'An accessible visible state for hover, keyboard focus and the selected destination.', '功能提案：讓滑鼠、鍵盤與觸控都有相同的定位線索；不需要開動畫或輸入指令才能導覽。', 'focus', ['src/specimens/focus.js'], { dependency: 'DOM / CSS', parameters: ['Active item'], tradeoff: 'A small cue that supports navigation. Keep the normal link text and focus outline.', sources: [{ title: 'MDN focus-visible', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible' }] });
add('ui-command', 'Secondary command panel', 'Interface', 'study', 'A bounded, non-shell command surface tied to the same visible representation controls.', '功能提案：指令只是第二介面；先有可點選的控制，再提供 help、view outline、view filled、reset。', 'command', ['src/specimens/command.js'], { dependency: 'DOM / native dialog', parameters: ['Representation', 'Allowlisted command'], tradeoff: 'Optional. Context-dependent commands explicitly report unavailability and never execute arbitrary input.' });
add('motion-reveal', 'Editorial aperture', 'Motion', 'accent', 'A user-triggered CSS mask reveals a short geometric heading.', '動畫提案：只放在篇章開頭或單一重點；不要把每個段落都套同樣的入場動畫。', 'reveal', ['src/specimens/reveal.js'], { dependency: 'Web Animations / CSS clip-path', parameters: ['Duration', 'Play / pause / reset'], tradeoff: 'The specimen demonstrates a visual entrance; production body text must render immediately.', sources: [{ title: 'MDN clip-path', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path' }] });
add('motion-linework', 'Linework trace', 'Motion', 'preferred', 'One SVG path moves from a diagrammatic outline to a complete geometric reading.', '動畫提案：可用於方法圖解、輪廓或組裝關係，幫助理解規則；不偽裝成加工刀路。', 'trace', ['src/specimens/trace.js'], { dependency: 'SVG / Web Animations', parameters: ['Progress', 'Replay', 'Duration'], tradeoff: 'An illustrative path, not toolpath generation or engineering analysis.', sources: [{ title: 'MDN SVG stroke-dasharray', url: 'https://developer.mozilla.org/en-US/docs/Web/SVG/Reference/Attribute/stroke-dasharray' }] });
add('motion-reflow', 'Assembly reflow / GSAP', 'Motion', 'study', 'Six DOM parts move between a packed layout and an exploded reading through one owner.', '動畫提案：適合介面或示意圖的狀態轉換；在明確分工下使用既有 GSAP，不與 Theatre 競爭相同屬性。', 'reflow', ['src/specimens/reflow.js'], { dependency: 'Existing GSAP 3.15.0', parameters: ['Layout', 'Separation', 'Duration'], tradeoff: 'DOM-only sequence. This is not the authored 3D motion core.', sources: [{ title: 'GSAP tween lifecycle', url: 'https://gsap.com/docs/v3/GSAP/gsap.to/' }] });
add('motion-theatre', 'Authored section study', 'Motion', 'preferred', 'An actual Studio-exported sequence separates and recombines a sectional SVG object through the agreed adapter.', '動畫提案：把敘事姿態交給 Theatre；提供播放、暫停、重播及可直接閱讀的靜態視圖。', 'theatre', ['src/motion/theatre/specimen.js', 'src/motion/theatre/motion.state.json'], { dependency: 'Existing Theatre Core / Studio 0.7.2 and application adapter', parameters: ['Play', 'Pause', 'Seek', 'Reset'], tradeoff: 'Website specimen only. It does not reproduce a client model or establish production authoring acceptance.', sources: [{ title: 'Theatre direct binding', url: 'https://www.theatrejs.com/docs/latest/getting-started/with-three-js' }] });
add('spatial-wirefield', 'Parametric wire field', 'Spatial', 'study', 'A deterministic wave grid with genuine amplitude, representation and camera-step controls.', '空間提案：先展示可調規則與同一幾何的不同閱讀方式；採按需繪製，預覽關閉即釋放場景。', 'wirefield', ['src/specimens/spatial.jsx'], { dependency: 'Existing Fiber 9.8.1 / Three 0.186.1', parameters: ['Amplitude', 'Surface / wireframe', 'Rotate', 'Reset'], tradeoff: 'Unitless generated geometry, not structural simulation. One canvas per open specimen.', sources: [{ title: 'Fiber demand rendering', url: 'https://r3f.docs.pmnd.rs/advanced/scaling-performance' }] });
add('spatial-hatch', 'Technical hatch material', 'Spatial', 'accent', 'An original derivative-aware GLSL hatch over the same generated geometry.', '材質提案：用灰階線密度表達表面方向，橘色只標示參考線；保留一般表面模式作比較。', 'hatch', ['src/specimens/spatial.jsx', 'src/specimens/hatch.js'], { dependency: 'Existing Three ShaderMaterial; no postprocessing', parameters: ['Hatch density', 'Amplitude', 'Rotate'], tradeoff: 'Illustrative material only. No stress, heat or measured performance is encoded.', sources: [{ title: 'Three ShaderMaterial', url: 'https://threejs.org/docs/pages/ShaderMaterial.html' }] });
add('spatial-ascii', 'ASCII height section', 'Spatial', 'accent', 'A real character-density projection of a small procedural height field.', '第二語言提案：只把幾何轉成 ASCII；正文、導覽與重要數據仍維持一般 HTML。', 'ascii', ['src/specimens/ascii.js'], { dependency: 'Deterministic JavaScript / text', parameters: ['Phase', 'Density', 'Reset'], tradeoff: 'Optional secondary representation; the diagram has an equivalent description and is hidden from screen readers.' });
const feedback = [
  ['type', 'Word planes / editorial depth', 'Word planes fan along different local axes while preserving a readable heading.', '文字不是整塊漂浮：把 FORM、SYSTEM、MAKE 視為不同厚度的字面；展開、聚焦與回復各有清楚的空間關係。', 'Chapter headings, short anthology labels; keep body copy stationary.', 'Fan / focus / choose a word'],
  ['glyph', 'Identity mechanisms / three rules', 'A gimbal, network and interlock reuse five parts with three distinct motion rules.', '身份動態：FORM 用旋轉軸、SYSTEM 用節點深度、MAKE 用咬合與分離。三者有同一套材質語言，但不套相同動畫。', 'Section marks and a brief owner-triggered identity study.', 'Choose logic / open / close'],
  ['key', 'Tactile key / press and release', 'A raised icon key compresses in depth and changes the actual adjacent representation.', '物件回饋：按下是壓縮、放開是回彈；功能狀態立即切換，不等待動畫結束。滑鼠、Enter、Space 都可操作。', 'Scene tools and representation switches; one localized key, not every page button.', 'Pointer down / cancel / keyboard / toggle'],
  ['card', 'Evidence card / separated layers', 'A generated drawing, its rule and its editorial label separate into three depth planes.', '卡片回饋：指向時有受限制的視差；點選後拆解規則、幾何與標籤。手機可直接按 Inspect layers，資訊不藏在 hover。', 'Case-study cover or Lab specimen; only use supplied approved media in production.', 'Pointer tilt / tap / inspect / assemble'],
  ['navigation', 'Navigation / depth detents', 'Selected chapter plates move to the reading plane; nearby focus remains a smaller cue.', '導覽回饋：選中項目前進到閱讀平面，聚焦只是較小的抬升；文字內容立即切換，路徑不依賴動畫。', 'A local chapter switcher with normal buttons; eventual route links keep native semantics.', 'Focus / select / next section'],
  ['panel', 'Disclosure / hinged covers', 'Two covers rotate about their outer edges while detail text opens in the normal document.', '面板回饋：開啟像打開構件外殼，而不是整個面板縮放。鉸鏈是裝飾，內容照一般文件閱讀與展開。', 'Method notes, technical annotations and optional metadata disclosure.', 'Open / close / expanded state'],
];
for (const [variant, name, description, proposal, use, trigger] of feedback) {
  add(`feedback-${variant}`, name, 'Spatial feedback', ['card', 'key', 'navigation'].includes(variant) ? 'preferred' : 'study', description, proposal, 'feedback', ['src/spatial-feedback/dom.js', 'src/spatial-feedback/response.js', 'preview/feedback.css'], {
    variant, collection: 'spatial-feedback-v1', dependency: 'CSS perspective / original interruptible response owner; no additional package',
    parameters: [trigger, 'Precise / elastic response', 'Perspective'],
    tradeoff: `${use} CSS transformed surfaces are 2.5D, with no mesh lighting or occlusion. This is an original UI specimen, not professional work.`,
    fallback: 'Semantic HTML controls and readable output remain in the document. Perspective is decorative.',
    reducedMotion: 'State changes apply immediately. No interpolated transforms, no pointer parallax, no autoplay.',
    sources: [{ title: 'MDN: perspective and local vanishing points', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/perspective' }, { title: 'MDN: preserve-3d and flattening constraints', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/transform-style' }, { title: 'W3C: animation from interactions', url: 'https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html' }],
    ...(variant === 'key' ? { license: 'Original response code; Lucide icon under ISC', notices: ['licenses/icons-lucide.txt'] } : {}),
  });
}
add('feedback-assembly', 'Spatial score / curved ribs', 'Spatial feedback', 'preferred', 'Nine curved ribs gather, fan, hold and return through an authored camera and assembly score. Each rib can be picked and lifted for inspection.', '主提案：有節奏的收束、扇開、停留、回組；鏡頭與組裝交給 Theatre，個別構件的點選與檢視在獨立層級回饋。不是永遠自轉的展示模型。', 'assembly', ['src/spatial-feedback/assembly.jsx', 'src/spatial-feedback/geometry.js', 'preview/feedback.css', 'src/motion/theatre/spatial/binding.js', 'src/motion/theatre/spatial/motion.state.json', 'src/motion/theatre/spatial/motion.manifest.json'], {
  collection: 'spatial-feedback-v1', dependency: 'Existing R3F 9.8.1 / Three 0.186.1 / Theatre 0.7.2; unchanged application adapter',
  parameters: ['Play / pause / seek', 'Nine raycast or numbered selections', 'Inspection turn', 'Surface / wire', 'Reset'],
  tradeoff: 'True WebGL geometry, metal lighting and perspective; user-activated canvas. Generated unitless study, not an engineering or client model. No new package.',
  fallback: 'Live static SVG projection and numbered selection controls, available without WebGL.',
  reducedMotion: 'Playback disabled; manual timeline poses and selected-part state apply directly, with no decorative interpolation.',
  sources: [{ title: 'R3F: raycast events and propagation', url: 'https://r3f.docs.pmnd.rs/api/events' }, { title: 'R3F: demand rendering and resource lifecycle', url: 'https://r3f.docs.pmnd.rs/advanced/scaling-performance' }, { title: 'Theatre: Studio transactions and save export', url: 'https://www.theatrejs.com/docs/latest/api/studio' }],
});
const applications = {
  font: ['Word-plane typography', ['feedback-type'], ['Lift heading'], '短標題按字詞展開、抬升與返回；原本的文字、字級、字重控制保留，正文不動。', 'Word spans own transforms; CSS font parameters remain independent.', ['src/specimens/assets.js']],
  icons: ['Tactile icon inspection', ['feedback-key', 'feedback-card'], ['Inspect a glyph', 'Press / release / cancel'], '直接作用於每個真實 SVG 圖示：點選提起，按下壓縮，取消返回。下載仍保留來源的原始檔案。', 'Fixed labeled buttons own input; inner glyph rigs own depth. Flat glyph shapes are preserved.', ['src/specimens/assets.js']],
  glyphs: ['Identity mark plates', ['feedback-glyph'], ['Inspect FORM / SYSTEM / MAKE'], '同一組原創身份圖形，各自以不同軸向開啟；清楚呈現三個主題的差異。', 'Mark plates use CSS perspective; these are not volumetric meshes.', ['src/specimens/assets.js']],
  palette: ['Separated color plates', ['feedback-card'], ['Separate color plates'], '把色票變成可分離的表面；文字與實際對比數值維持固定，避免材質效果干擾判讀。', 'Only decorative color surfaces move; contrast is measured from the original color pairs.', ['src/specimens/assets.js']],
  focus: ['Navigation detents', ['feedback-navigation'], ['Select a navigation state'], '將目前選取的項目帶到閱讀平面；原本 Tab、Enter 與選取狀態保留，按鈕範圍固定。', 'Inner plates move; semantic buttons retain stable hit regions.', ['src/specimens/focus.js']],
  command: ['Layered representation state', ['feedback-panel', 'feedback-key'], ['Outline / Filled from either interface'], '相同的 Outline／Filled 狀態直接改變物件各層，指令與按鈕共享同一個結果。', 'The command whitelist is unchanged; faces are CSS planes, not camera-controlled geometry.', ['src/specimens/command.js']],
  reveal: ['Hinged aperture', ['feedback-panel'], ['Play / pause / reset reveal'], '揭示時像打開構件外殼；左右鉸鏈讀取原有 reveal 的同一進度，不增加獨立播放時鐘。', 'Existing native animation owns time/clip; decorative leaves follow its evaluated progress.', ['src/specimens/reveal.js']],
  trace: ['Construction-line stack', ['feedback-card'], ['Plane separation', 'Trace progress'], '將基準面、座標線與實際 SVG 描邊分成三層；可一邊調整分層，一邊檢視描繪進度。', 'Stroke animation owns dash offset; a separate rig owns plane transforms. No toolpath claim.', ['src/specimens/trace.js']],
  reflow: ['Part-face inspection', ['feedback-card', 'feedback-key'], ['Inspect six parts', 'Packed / Separated'], '原本 GSAP 排列加上可逐件檢視的構件表面；外層排列與內層抬升各有一個控制者。', 'GSAP owns outer placement; direct response owns nested face transforms.', ['src/specimens/reflow.js']],
  theatre: ['Authored section with local inspection', ['feedback-assembly'], ['Inspect nine sections', 'Authored play / seek'], '沿用真正的 Theatre 編排，加入構件厚度與逐件抽出；檢視時暫停編排，避免互動與時間軸互相搶控制。', 'Existing genuine export/adapter owns outer groups; local inspection owns inner groups. No fabricated keyframes.', ['src/motion/theatre/specimen.js', 'src/specimens/section-geometry.js']],
  wirefield: ['Picked field-band lift', ['feedback-assembly'], ['Pick mesh band / numbered band', 'Baseline / Spatial'], '滑鼠點到的區段與編號按鈕共享選取；實際頂點局部抬起、法線重新計算，靜止後停止渲染。', 'CPU geometry buffers, bounds and raycasts agree. One response owns vertices; stepped camera remains independent.', ['src/specimens/spatial.jsx']],
  hatch: ['Material response to selected geometry', ['feedback-assembly'], ['Pick field band', 'Hatch density'], '選取真實幾何區段後，抬升與 hatch 參考帶一起回應；線密度仍是可調材質參數，不是假裝的受力分析。', 'The same response owns CPU geometry and shader focus uniforms. No postprocessing or simulation package.', ['src/specimens/spatial.jsx', 'src/specimens/hatch.js']],
  ascii: ['Height-range planes', ['feedback-card', 'feedback-type'], ['Low / Middle / High', 'Slice separation'], '依真實高度值拆成低、中、高三個 ASCII 平面；可以隔離某段資料，字元會隨程序參數重新計算。', 'Deterministic text slices of the existing height field; CSS perspective, not WebGL or professional analysis.', ['src/specimens/ascii.js']],
};
for (const material of materials) {
  const application = applications[material.demo]; if (!application) continue;
  const [name, basis, parameters, proposal, ownership, files] = application;
  material.appliedFeedback = { revision: 'applied-feedback-v1', name, basis, ownership, review: 'New application proposal; retains the existing material ID and Saved status.' };
  material.proposal += `\n\nRound 04：${proposal}`;
  material.parameters = [...new Set([...material.parameters, 'Feedback: Baseline / Spatial', ...parameters])];
  material.sourceFiles = [...new Set([...material.sourceFiles, ...files, 'src/specimens/helpers.js', 'src/applied-feedback/controls.js', 'src/spatial-feedback/response.js', 'preview/applied.css'])];
  material.reducedMotion = ['theatre'].includes(material.demo) ? 'Authored playback disabled; manual poses and part selection remain available with direct feedback states.' : 'No automatic motion. Direct interaction feedback snaps to its target. Existing reveal/trace playback resolves to its complete state.';
  material.sources.push({ title: 'W3C: interaction animation controls', url: 'https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html' });
}
await writeFile(path.join(root, 'catalog/applied-feedback.manifest.json'), JSON.stringify({ schemaVersion: 1, role: 'uiux-designer', revision: 'applied-feedback-v1', publicationApproval: false, reviewSurface: '/?collection=applied-feedback', materials: materials.filter(m => m.appliedFeedback).map(m => ({ id: m.id, category: m.category, ...m.appliedFeedback })) }, null, 2) + '\n');
await writeFile(path.join(root, 'catalog/materials.json'), JSON.stringify({ schemaVersion: 1, role: 'uiux-designer', title: 'Material studies', reviewedAt: '2026-10-07', categories: ['Spatial feedback', 'Typography', 'Icons', 'Identity', 'Interface', 'Motion', 'Spatial'], materials }, null, 2) + '\n');
console.log(`Wrote ${materials.length} individually reviewable proposals.`);
