import { useEffect, useRef, useState } from 'react'
import { PROFILE } from '../content/portfolio'

export function About() {
  return <article className="profile-page">
    <header className="page-intro" data-reading-anchor><p className="eyebrow">ABOUT</p><h1 className="page-heading" tabIndex={-1}>Chia-Hsuan Chao</h1><p className="intro-deck">JosHsuan / Computational designer and XR developer</p></header>
    <div className="about-grid" data-reading-anchor><div className="about-narrative"><p>My research and professional work concern computational geometry, material behavior and design-to-fabrication workflows. Projects include bending-active metal panels, robotic timber assembly, custom fabrication machines and extended-reality interfaces.</p><p>After studying landscape architecture at Fu Jen Catholic University, I completed a master’s degree at National Cheng Kung University with a thesis on computational simulation and pattern development for bending-active metal panels. At PKD Engineering Consultants, I worked on facade rationalization, coordination with structural and detail specialists, and the conversion of three-dimensional models into fabrication drawings.</p><p>The MAS in Architecture and Digital Fabrication at ETH Zürich extended this work to collaborative timber construction and motion-capture-based assembly guidance. As a research assistant on EchoXR at Gramazio Kohler Research, I developed VR interactions, tracking, multiplayer networking and material rendering for collaborative spatial-acoustics exploration.</p><a className="inline-link" href="/resume.html" target="_blank" rel="noreferrer">Open résumé / print <span aria-hidden="true">↗</span></a></div><aside className="practice-list"><h2>Areas of practice</h2><dl><div><dt>Computational geometry</dt><dd>Parametric modeling, Python, C#</dd></div><div><dt>Extended reality</dt><dd>Unity interfaces, tracking, shared environments</dd></div><div><dt>Digital fabrication</dt><dd>Robotic assembly, toolpaths, material prototypes</dd></div><div><dt>Facade development</dt><dd>Geometry rationalization, coordination, fabrication drawings</dd></div></dl></aside></div>
    <section className="profile-section" data-reading-anchor><div className="section-label"><h2>Selected experience</h2><span>RESEARCH / PRACTICE</span></div><dl className="timeline"><div><dt>2024–25</dt><dd><h3>Gramazio Kohler Research, ETH Zürich</h3><p>Research assistant / EchoXR</p><span>VR/AR development, tracking, multiplayer networking and material rendering.</span></dd></div><div><dt>2021–22</dt><dd><h3>PKD Engineering Consultants</h3><p>Computational designer & BIM engineer</p><span>Geometry rationalization, facade coordination and fabrication drawings.</span></dd></div><div><dt>2018–19</dt><dd><h3>sKY Associative Maker Space</h3><p>Part-time facilities technician</p><span>Fabrication facilities, laser cutters and 3D printers.</span></dd></div></dl></section>
    <section className="profile-section" data-reading-anchor><div className="section-label"><h2>Education</h2><span>DESIGN / COMPUTATION</span></div><dl className="timeline"><div><dt>2023–24</dt><dd><h3>ETH Zürich</h3><p>MAS in Architecture & Digital Fabrication</p></dd></div><div><dt>2017–20</dt><dd><h3>National Cheng Kung University</h3><p>Master of Architecture / Design, Computing & Digital Fabrication</p></dd></div><div><dt>2012–17</dt><dd><h3>Fu Jen Catholic University</h3><p>Bachelor of Landscape Architecture</p></dd></div></dl></section>
    <section className="profile-section" data-reading-anchor><div className="section-label"><h2>Selected publications</h2></div><div className="publication"><span>2025 / IHIET</span><a href="https://doi.org/10.54941/ahfe1006713" target="_blank" rel="noreferrer">EchoXR: A Collaborative VR Framework for Spatial Acoustics in Architectural Design ↗</a><p>Fabio Scotto, Chia-Hsuan Chao, Giacomo Montiani, Achilleas Xydis, Fabio Gramazio, Matthias Kohler.</p></div><div className="publication"><span>2023 / CAADRIA</span><a href="https://doi.org/10.52842/conf.caadria.2023.2.201" target="_blank" rel="noreferrer">Bending-Active Metal Panel Deformation: Control through Computational Simulation and Pattern Development ↗</a><p>Chia-Hsuan Chao and Kane Yanagawa.</p></div></section>
    <a className="next-project" href="#/contact" data-reading-anchor><span className="eyebrow">EMAIL / PROFILES</span><span>Contact</span><span aria-hidden="true">↗</span></a>
  </article>
}

export function Contact() {
  const [status, setStatus] = useState('')
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined)
  useEffect(() => () => clearTimeout(timer.current), [])
  const copy = async () => {
    try { await navigator.clipboard.writeText(PROFILE.email); setStatus('Email address copied.') }
    catch { setStatus('Copy is unavailable here. Select the address below or use Email me.') }
    clearTimeout(timer.current)
    timer.current = setTimeout(() => setStatus(''), 5000)
  }
  return <article className="contact-page"><header className="page-intro" data-reading-anchor><p className="eyebrow">CONTACT</p><h1 className="page-heading" tabIndex={-1}>Contact</h1><p className="intro-deck">Research enquiries and design collaborations.</p></header><div className="contact-address" data-reading-anchor><span className="eyebrow">EMAIL</span><a href={`mailto:${PROFILE.email}`}>{PROFILE.email}</a><div className="contact-actions"><a className="primary-button" href={`mailto:${PROFILE.email}`}>Email me <span aria-hidden="true">↗</span></a><button className="secondary-button" onClick={copy}>Copy address</button></div><p className="copy-status" role="status">{status}</p></div><div className="contact-links" data-reading-anchor><a href={PROFILE.github} target="_blank" rel="noreferrer"><span>01 / GITHUB</span><span>Code & repositories</span><span aria-hidden="true">↗</span></a><a href="https://gramaziokohler.arch.ethz.ch/web/e/team/370.html" target="_blank" rel="noreferrer"><span>02 / ETH ZÜRICH</span><span>Research profile</span><span aria-hidden="true">↗</span></a></div><p className="contact-note" data-reading-anchor>Your email opens in your own mail application. This site does not collect form submissions or use analytics cookies.</p></article>
}
