import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import { readContentSource, filesUnder } from './content-source';

const snapshot = await readContentSource();
await mkdir('src/generated', { recursive: true });
await writeFile('src/generated/public-content.json', JSON.stringify(snapshot, null, 2) + '\n');

// Concrete routes support a truly empty export without a fictional [slug] entry.
const routeRoot = resolve('src/app/(entries)');
const marker = '// Generated by scripts/export-content.ts. Do not edit.\n';
await mkdir(routeRoot, { recursive: true });
const wanted = new Map<string, string>();
for (const kind of ['projects', 'research'] as const) {
  for (const entry of snapshot[kind]) {
    const file = resolve(routeRoot, kind, entry.slug, 'page.tsx');
    wanted.set(file, marker + `import { EntryDetail } from '@/components/content/EntryDetail';\nexport const metadata = ${JSON.stringify({ title: entry.title, description: entry.summary })};\nexport default function Page() { return <EntryDetail kind=${JSON.stringify(kind)} slug=${JSON.stringify(entry.slug)} />; }\n`);
  }
}
for (const file of await filesUnder(routeRoot)) {
  if (!file.startsWith(routeRoot + sep)) throw new Error('Generated route escaped its directory.');
  if (!(await readFile(file, 'utf8')).startsWith(marker)) throw new Error(`Unexpected file in generated route directory: ${file}`);
  if (!wanted.has(file)) await unlink(file);
}
for (const [file, contents] of wanted) {
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, contents);
}
console.log(`Exported public snapshot and ${wanted.size} detail routes.`);
