import React,{Suspense,lazy,useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {role,studies} from './catalog.js';
import {createInput,pointerProgress,scrollProgress} from './input.js';
import {sample,timing} from './model.js';
import {load,parseReview,parseUIUX} from './review-state.js';
import {references} from './references.js';
const Stage=lazy(()=>import('./engine.jsx').then(m=>({default:m.Stage})));
const download=(name,content,type='application/json')=>{const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
class Boundary extends React.Component{state={failed:false};static getDerivedStateFromError(){return{failed:true};}componentDidCatch(error){this.props.onFailure(error.message);}render(){return this.state.failed?<p>Live rendering unavailable. See the captured comparison below.</p>:this.props.children;}}
function TimingCharts(){
 return <div className="timing-charts">{[['speed','Velocity / normalized distance per second',0,.35],['acceleration','Acceleration / normalized distance per second²',-.18,.18]].map(([key,label,min,max])=><div key={key}><p>{label}</p><svg viewBox="0 0 300 74" role="img" aria-label={label}><line x1="0" x2="300" y1={70-(0-min)/(max-min)*65} y2={70-(0-min)/(max-min)*65} stroke="#425963"/>{[false,true].map(smooth=><path key={String(smooth)} fill="none" stroke={smooth?'#e3a173':'#6b8089'} d={Array.from({length:61},(_,i)=>`${i?'L':'M'}${i*5},${70-(timing(i/60,smooth)[key]-min)/(max-min)*65}`).join(' ')}/>)}</svg></div>)}<p>Both graphs assume a six-second traversal. They do not measure your hand or wheel velocity.</p></div>;
}
function App(){
 const initial=useMemo(()=>load(),[]),[review,setReview]=useState(initial.data),[storageBlocked,setStorageBlocked]=useState(initial.blocked);
 const params=new URLSearchParams(location.search),[id,setId]=useState(studies.some(s=>s.id===params.get('study'))?params.get('study'):studies[0].id),study=studies.find(s=>s.id===id);
 const input=useMemo(()=>createInput(params.has('u')?Number(params.get('u')):.5),[]),[mode,setMode]=useState('pointer'),[status,setStatus]=useState('Loading local scene…'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('all');
 const [reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),[explicitMotion,setExplicitMotion]=useState(false),staticMode=reduced&&!explicitMotion;
 const stage=useRef(),runway=useRef(),readout=useRef(),progress=useRef(),phase=useRef(),focusRail=useRef(),metrics=useRef(),marker=useRef(),ownFile=useRef(),uiuxFile=useRef();
 const onReady=useCallback(()=>setStatus('Ready · no autonomous playback'),[]),onFailure=useCallback(message=>{setError(message);input.set(.3,'equivalent');setStatus('Captured checkpoint · 30%');},[input]);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>{setReduced(media.matches);setExplicitMotion(false);};media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
 useEffect(()=>{if(storageBlocked)return;try{localStorage.setItem(role.key,JSON.stringify(review));}catch{setStorageBlocked(true);}},[review,storageBlocked]);
 useEffect(()=>{
  const update=()=>{const u=input.u,p=sample(study.id,u,'b'),t=timing(u,true);if(readout.current)readout.current.textContent=`${Math.round(u*100)}%`;if(progress.current)progress.current.style.width=`${u*100}%`;if(stage.current)stage.current.setAttribute('aria-valuenow',String(Math.round(u*100)));if(marker.current)marker.current.setAttribute('x1',String(u*300)),marker.current.setAttribute('x2',String(u*300));if(phase.current){const index=Math.min(2,Math.floor(u*3));phase.current.querySelectorAll('[data-phase]').forEach((el,i)=>el.setAttribute('aria-current',i===index?'step':'false'));}if(metrics.current)metrics.current.textContent=study.id==='timing'?`B · progress ${t.distance.toFixed(2)} / velocity ${t.speed.toFixed(3)} s⁻¹ / acceleration ${t.acceleration.toFixed(3)} s⁻²`:`Input ${u.toFixed(3)} · ${staticMode?'Static checkpoint':p.materialProgress!==undefined?'Matched A/B camera and light · '+p.materialMode:p.owner==='theatre'?'Authored sequence seek':`B lens ${Math.round(12/Math.tan(p.fov*Math.PI/360))} mm equivalent`}`;};
  update();return input.subscribe(update);
 },[input,study,staticMode]);
 useEffect(()=>{if(staticMode)input.set(.5,'equivalent');},[staticMode,input]);
 useEffect(()=>{const update=()=>focusRail.current?.querySelectorAll('[data-band]').forEach((el,i)=>el.setAttribute('aria-current',i===Math.round(input.u*16)?'true':'false'));update();return input.subscribe(update);},[id,input]);
 useEffect(()=>{if(mode!=='scroll'||staticMode||error)return;const scroll=()=>{if(!runway.current)return;const r=runway.current.getBoundingClientRect();input.set(scrollProgress(scrollY,scrollY+r.top,r.height,innerHeight),'scroll');};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);scroll();return()=>{removeEventListener('scroll',scroll);removeEventListener('resize',scroll);};},[mode,input,staticMode,error]);
 function select(next){setId(next);setError('');const url=new URL(location.href);url.searchParams.set('study',next);url.searchParams.delete('u');history.replaceState(null,'',url);}
 function selectMode(next){input.select(next);setMode(next);}
 function pointer(event){if(error||staticMode||event.pointerType==='touch'&&event.type==='pointermove'&&!event.buttons)return;const rect=stage.current.getBoundingClientRect();input.set(pointerProgress(event.clientX,rect.left,rect.width),'pointer');}
 function keys(event){let next=input.u;if(event.key==='ArrowRight'||event.key==='ArrowUp')next+=.025;else if(event.key==='ArrowLeft'||event.key==='ArrowDown')next-=.025;else if(event.key==='Home')next=0;else if(event.key==='End')next=1;else return;event.preventDefault();if(!staticMode&&!error)input.set(next,'equivalent');}
 function save(variant){setReview(r=>({...r,saved:[...r.saved.filter(s=>!(s.id===id&&s.variant===variant)),{id,variant,u:input.u,mode}]}));setNotice(`Saved ${variant.toUpperCase()} at ${Math.round(input.u*100)}%.`);}
 async function importFile(event,uiux){const file=event.target.files?.[0];if(!file)return;try{if(file.size>500000)throw new Error('File exceeds 500 KB.');const text=await file.text(),value=JSON.parse(text);if(uiux){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)),sha=[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');setReview(r=>({...r,uiuxBasis:parseUIUX(value,sha)}));}else setReview(parseReview(value));setNotice('Imported; original file is unchanged.');}catch(e){setNotice(e.message);}finally{event.target.value='';}}
 function exportReview(){download(`${role.id}-interaction-choices.json`,JSON.stringify({...review,exportedAt:new Date().toISOString(),current:{id,u:input.u,mode},sourceOrigin:location.origin},null,2));setNotice('Exported the review JSON.');}
 const matched=review.uiuxBasis?.saved.filter(s=>study.basis.includes(s.id))??[];
 return <>
 <header className="topbar"><a href="/" className="wordmark">{role.name}<span>Local research · 02</span></a><nav aria-label="Workspaces"><a href="http://127.0.0.1:4175/" target="_blank" rel="noreferrer">UIUX desk ↗</a><a href={role.other} target="_blank" rel="noreferrer">{role.otherName} ↗</a><a href="#review">Review ({review.saved.length})</a></nav></header>
 <main><section className="intro"><p className="eyebrow">Interactive proposals / isolated role workspace</p><h1>{role.title}</h1><p>{role.description}</p><p className="material-shortcuts">New texture / shader studies: <a href="/?study=bamboo-grain">Directional grain</a> · <a href="/?study=bamboo-pbr">PBR maps</a> · <a href="/?study=surface-contours">Contours</a> · <a href="/?study=surface-focus">Attention bands</a></p></section>
 <nav className="study-nav" aria-label="Studies">{studies.map((s,i)=><button key={s.id} aria-current={id===s.id?'page':undefined} onClick={()=>select(s.id)}><span>{String(i+1).padStart(2,'0')}</span>{s.title}</button>)}</nav>
 <section ref={runway} className={`runway ${mode==='scroll'&&!staticMode?'scroll-mode':''}`}>
 <div className="frame">
 <div className="frame-heading"><div><p className="eyebrow">{String(studies.indexOf(study)+1).padStart(2,'0')} / {studies.length} · Controlled comparison</p><h2>{study.title}</h2></div><div className="input-mode" aria-label="Choose the single input source"><button aria-pressed={mode==='pointer'} onClick={()=>selectMode('pointer')}>Mouse position</button><button aria-pressed={mode==='scroll'} onClick={()=>selectMode('scroll')}>Page scroll</button></div></div>
 <div className="canvas-wrap" ref={stage} role="slider" tabIndex={0} aria-label="Comparison progress. Move horizontally, or use arrow keys. Touch drag is equivalent." aria-valuemin="0" aria-valuemax="100" aria-valuenow="50" onPointerDown={pointer} onPointerMove={pointer} onKeyDown={keys}>
 <div className="view-label a">{study.a}</div><div className="view-label b">{study.b}</div><div className="center-rule"/>
 {!error?<Boundary key={id} onFailure={onFailure}><Suspense fallback={<p className="loading">Loading the local renderer…</p>}><Stage {...{study,input,onReady,onFailure}} reduced={staticMode}/></Suspense></Boundary>:<img className="fallback" src={`/assets/captures/${id}.png`} alt={`${study.a} compared with ${study.b}`}/>}
 <div className="input-hint">{error?'Captured checkpoint · 30%':staticMode?'Reduced motion · fixed midpoint':mode==='pointer'?'Move horizontally · one shared progress':'Scroll the page · one shared progress'}</div>
 </div>
 <div className="transport"><div className="progress-track"><div ref={progress}/></div><output ref={readout}>50%</output><span>{status}</span><button onClick={()=>save('a')}>Save A</button><button onClick={()=>save('b')}>Save B</button></div>
 {['proximity','finish'].includes(id)&&<div className="focus-rail" ref={focusRail} aria-label="Focused rib index">{Array.from({length:17},(_,i)=><span key={i} data-band>{String(i+1).padStart(2,'0')}</span>)}</div>}
 <div className="chapter-rail" ref={phase}>{(id==='reader'?['Overview','Separate','Return']:['Form','Structure','Detail']).map((label,i)=><span data-phase key={label}>{String(i+1).padStart(2,'0')} / {label}</span>)}<small>Stable HTML labels · shared progress</small></div>
 {error&&<p className="motion-notice">{error} The comparison is a captured still.</p>}
 {staticMode&&!error&&<p className="motion-notice">Reduced motion uses a stable midpoint and captured comparisons. <button onClick={()=>setExplicitMotion(true)}>Enable manual motion for this review</button></p>}
 </div></section>
 <section className="explanation"><div><p className="eyebrow">The interaction</p><h3>{study.question}</h3><p className="mapping">{study.mapping}</p><p>{study.mechanism}</p><p><strong>Suggested use.</strong> {study.use}</p><p className="limit"><strong>Boundary.</strong> {study.limit}</p></div><aside><p className="eyebrow">Signal / output</p><svg className="signal" viewBox="0 0 300 84" role="img" aria-label={study.id==='timing'?'Linear and minimum-jerk distance over normalized progress':'Normalized input progress'}><path d="M0 80 L300 4" stroke="#6b8089" fill="none"/><path d={Array.from({length:61},(_,i)=>`${i?'L':'M'}${i*5},${80-timing(i/60,true).distance*76}`).join(' ')} stroke="#e3a173" fill="none"/><line ref={marker} y1="0" y2="84" stroke="#eae7dd"/></svg><p>Time-law reference: gray linear distance; amber minimum-jerk distance.</p><output className="metrics" ref={metrics}/>{study.id==='timing'&&<TimingCharts/>}<p className="eyebrow">UIUX connection</p><p>{study.basis.join(' · ')}</p><p>{review.uiuxBasis?`${matched.length} matching imported UIUX choices; revision still needs review.`:'Owner Saved preferences are unknown. These are candidate mappings to existing UIUX studies.'}</p><a href="http://127.0.0.1:4175/" target="_blank" rel="noreferrer">Review the original UIUX workspace ↗</a></aside></section>
 <section className="evidence"><details><summary>Sources, implementation and captured comparison</summary><div className="evidence-grid"><div><ul>{study.sources.map(key=><li key={key}><a href={references[key].url} target="_blank" rel="noreferrer">{references[key].label} ↗</a></li>)}</ul><p>Original specimen geometry and local CC0 studio environment. Texture studies add an independent CC0 bamboo-wall swatch and pinned MIT simplex source; mapping and material logic are original. See the source register for pins and limits.</p><p><a href={`/assets/captures/${id}-late.png`}>Second checkpoint · u = 0.70</a></p><a href="/catalog/sources.json">Source register</a> · <a href="/catalog/material-recipes.json">Material recipes</a> · <a href="/catalog/studies.json">Study catalog</a> · <a href="/licenses/README.md">Licenses</a></div><a href={`/assets/captures/${id}.png`}><img src={`/assets/captures/${id}.png`} alt={`Captured u = 0.30: ${study.a} and ${study.b}`} loading="lazy"/></a></div></details></section>
 <section className="review" id="review"><div className="review-title"><div><p className="eyebrow">Your review / stored only on this origin</p><h2>Keep the useful differences.</h2></div><div><button onClick={exportReview}>Export choices</button><button onClick={()=>ownFile.current.click()}>Import this role</button><button onClick={()=>uiuxFile.current.click()}>Import UIUX choices</button><input hidden type="file" accept="application/json,.json" ref={ownFile} onChange={e=>importFile(e,false)}/><input hidden type="file" accept="application/json,.json" ref={uiuxFile} onChange={e=>importFile(e,true)}/></div></div>
 <p aria-live="polite">{storageBlocked?'Browser storage is unavailable or invalid; use Export choices. Existing storage is not overwritten.':notice||'Save A and/or B at a meaningful progress point, then add a note.'}</p><label className="notes">Note for {study.title}<textarea maxLength={5000} value={review.notes[id]??''} onChange={e=>setReview(r=>({...r,notes:{...r.notes,[id]:e.target.value}}))} placeholder="What is useful? Where could it help a reader?"/></label>
 <div className="review-filters"><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>All proposals</button><button aria-pressed={filter==='saved'} onClick={()=>setFilter('saved')}>Saved only ({review.saved.length})</button></div>
 <div className="contact-sheet">{studies.filter(s=>filter==='all'||review.saved.some(x=>x.id===s.id)).map(s=><article key={s.id}><button className="poster-button" onClick={()=>{select(s.id);stage.current.scrollIntoView({block:'center'});}}><img src={`/assets/captures/${s.id}.png`} loading="lazy" alt={`${s.title} captured comparison`}/><h3>{s.title}</h3></button><p>{s.use}</p>{review.saved.filter(x=>x.id===s.id).map(x=><div className="saved-choice" key={x.variant}><button onClick={()=>{select(s.id);selectMode('pointer');input.set(x.u,'equivalent');stage.current.scrollIntoView({block:'center'});}}>Recall {x.variant.toUpperCase()} · {Math.round(x.u*100)}%</button><button aria-label={`Remove ${s.title} ${x.variant.toUpperCase()}`} onClick={()=>setReview(r=>({...r,saved:r.saved.filter(y=>y!==x)}))}>Remove</button></div>)}</article>)}</div>
 <details><summary>Imported UIUX provenance</summary>{review.uiuxBasis?<><p>Original source: {review.uiuxBasis.sourceOrigin} / {review.uiuxBasis.sourceKey}</p><code>{review.uiuxBasis.sha256}</code>{review.uiuxBasis.saved.map(s=><p key={s.id}><strong>{s.name}</strong> · {s.id} · {s.status}<br/>{s.note}</p>)}</>:<p>No owner export imported. Test fixtures and researcher suggestions never establish owner preferences.</p>}</details>
 </section></main><footer><span>Local proposals · no production integration or publication</span><a href="/catalog/studies.json">Readable catalog</a>{role.id==='3d-artist'&&<a href="/bench/index.html">Previous parameter bench (archive)</a>}</footer>
 </>;
}
createRoot(document.getElementById('root')).render(<App/>);
