export const references={
 bamboo:{label:'Poly Haven · Bamboo Wall / Amal Kumar / CC0',url:'https://polyhaven.com/a/bamboo_wall'},
 noise:{label:'stegu / Ashima Arts · pinned MIT simplex noise',url:'https://github.com/stegu/webgl-noise/tree/22434e04d7753f7e949e8d724ab3da2864c17a0f'},
 'three-material':{label:'Three.js · standard PBR material and data maps',url:'https://threejs.org/docs/pages/MeshStandardMaterial.html'},
 'three-color':{label:'Three.js · colour management',url:'https://threejs.org/manual/en/color-management.html'},
 'three-shader':{label:'Three.js · material shader extension / WebGL',url:'https://threejs.org/docs/pages/Material.html'},
 lusion:{label:'Lusion · native scroll / DOM and WebGL',url:'https://github.com/lusionltd/WebGL-Scroll-Sync/tree/d2f2c844b449878c760e3f435ab01c85ed5ee072'},
 r3f:{label:'React Three Fiber · demand rendering',url:'https://r3f.docs.pmnd.rs/advanced/scaling-performance'},
 'three-camera':{label:'Three.js · PerspectiveCamera',url:'https://threejs.org/docs/pages/PerspectiveCamera.html'},
 'three-curve':{label:'Three.js · Curve / arc-length sampling',url:'https://threejs.org/docs/pages/Curve.html'},
 'three-physical':{label:'Three.js · physical materials',url:'https://threejs.org/docs/pages/MeshPhysicalMaterial.html'},
 'three-buffer':{label:'Three.js · BufferGeometry',url:'https://threejs.org/docs/pages/BufferGeometry.html'},
 'three-bokeh':{label:'Three.js · depth / Bokeh shader reference',url:'https://github.com/mrdoob/three.js/blob/9b4a2ac29c63ccb43fd51c5661f2f873ac2c39b8/examples/jsm/shaders/BokehShader.js'},
 'three-post':{label:'Three.js · postprocessing',url:'https://threejs.org/manual/en/post-processing.html'},
 rapier:{label:'Rapier JS · pinned physics runtime',url:'https://github.com/dimforge/rapier.js/tree/v0.19.3'},
 theatre:{label:'Theatre · advanced input mapping',url:'https://www.theatrejs.com/docs/latest/manual/advanced'},
 tiffen:{label:'Tiffen · Black Pro-Mist reference',url:'https://tiffen.com/products/black-pro-mist-filter'},
};
