import {createRequire} from 'node:module';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {request} from 'node:http';
const {chromium,webkit,devices}=createRequire(new URL('../../../../../package.json',import.meta.url))('@playwright/test');
const executablePath='C:/Users/JosHsuan/AppData/Local/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-win64/chrome-headless-shell.exe';
const origin='http://127.0.0.1:4184',results=[],failures=[];
const httpStatus=options=>new Promise((resolve,reject)=>{const req=request(origin+'/',options,res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});
await mkdir(new URL('../verification/',import.meta.url),{recursive:true});
async function check(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS '+name);}catch(e){failures.push({name,error:e.message});console.log('FAIL '+name+' '+e.message.slice(0,200));}}
const wait=page=>page.waitForFunction(()=>window.__thesis?.inspect().ready,{},{timeout:40000});
const canvasGroup=page=>page.getByRole('group',{name:'Model inspection. Use left and right arrow keys, Home or End.'});
const activate=async page=>{await page.getByRole('button',{name:'Explore the model',exact:true}).click();await wait(page);};
const setProgress=async(page,value)=>{await canvasGroup(page).focus();await canvasGroup(page).press('Home');for(let i=0;i<Math.round(value/.025);i++)await canvasGroup(page).press('ArrowRight');await page.waitForTimeout(100);};
for(const profile of ['chromium','webkit','mobile']){
 const browser=await(profile==='webkit'?webkit:chromium).launch(profile==='webkit'?{headless:true}:{headless:true,executablePath});
 const context=await browser.newContext(profile==='mobile'?{...devices['Pixel 7']}:{viewport:{width:1440,height:1000},deviceScaleFactor:1});const page=await context.newPage();const errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>requests.push(r.url()));
 try{
  await check(profile+'/readable initial page and deferred model',async()=>{await page.goto(origin);await page.waitForTimeout(200);assert.equal(await page.locator('canvas').count(),0);assert(!requests.some(u=>u.endsWith('.glb')||u.endsWith('.hdr')));assert((await page.locator('h1').getAttribute('aria-label')).includes('Metal Panel'));assert.equal(await page.locator('main article').count(),3);assert(await page.locator('img[alt="Converted CAD assembly of the bending-active perforated metal surface"]').evaluate(i=>i.complete&&i.naturalWidth>0));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);});
  await check(profile+'/actual model, shader and edge output',async()=>{await activate(page);let state=await page.evaluate(()=>window.__thesis.inspect());assert.equal(state.model.triangles,131881);assert.equal(state.model.publishable,false);const before=await page.locator('canvas').screenshot();await page.getByRole('button',{name:'Contours',exact:true}).click();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>window.__thesis.inspect().representation),'contours');assert(!before.equals(await page.locator('canvas').screenshot()),'Contours did not change actual pixels');await page.getByRole('button',{name:'Edges',exact:true}).click();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>window.__thesis.inspect().representation),'edges');assert(!before.equals(await page.locator('canvas').screenshot()),'Edges did not change pixels');await page.getByRole('button',{name:'Material',exact:true}).click();});
  await check(profile+'/reversible keyboard, pointer or touch and idle frames',async()=>{await page.getByRole('button',{name:'Inspect',exact:true}).click();await setProgress(page,.25);const before=await page.evaluate(()=>window.__thesis.inspect().pose);const first=await page.locator('canvas').screenshot();await setProgress(page,.75);assert.notDeepEqual(await page.evaluate(()=>window.__thesis.inspect().pose.position),before.position);await setProgress(page,.25);assert.deepEqual(await page.evaluate(()=>window.__thesis.inspect().pose),before);assert(first.equals(await page.locator('canvas').screenshot()),'Same progress did not restore same pixels');const box=await canvasGroup(page).boundingBox();if(profile==='mobile')await page.touchscreen.tap(box.x+box.width*.65,box.y+box.height*.5);else await page.mouse.move(box.x+box.width*.65,box.y+box.height*.5);await page.waitForTimeout(160);assert(Math.abs(await page.evaluate(()=>window.__thesis.inspect().u)-.65)<.01);const frames=await page.evaluate(()=>window.__thesis.inspect().frames);await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>window.__thesis.inspect().frames),frames);});
  await check(profile+'/scroll has exclusive camera ownership',async()=>{await page.getByRole('button',{name:'Follow page',exact:true}).click();await page.locator('#system').scrollIntoViewIfNeeded();await page.waitForTimeout(200);let a=await page.evaluate(()=>window.__thesis.inspect());assert.equal(a.mode,'story');const box=await canvasGroup(page).boundingBox();await page.mouse.move(box.x+box.width*.9,box.y+30);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.__thesis.inspect().u),a.u);await page.mouse.wheel(0,300);await page.waitForTimeout(250);const b=await page.evaluate(()=>window.__thesis.inspect());if(profile!=='mobile')assert.notEqual(b.u,a.u);await page.getByRole('button',{name:'Fixed',exact:true}).click();let fixed=await page.evaluate(()=>window.__thesis.inspect().u);await page.mouse.wheel(0,180);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>window.__thesis.inspect().u),fixed);});
  await check(profile+'/re-entry disposes and restores resources',async()=>{const before=await page.evaluate(()=>window.__thesis.inspect().memory);await page.getByRole('button',{name:'Close 3D',exact:true}).click();await page.waitForTimeout(100);assert.equal(await page.locator('canvas').count(),0);await activate(page);const after=await page.evaluate(()=>window.__thesis.inspect().memory);assert(after.geometries<=before.geometries&&after.textures<=before.textures,"Re-entry grew GPU resource counts");assert.deepEqual(errors,[]);await canvasGroup(page).scrollIntoViewIfNeeded();await page.screenshot({path:fileURLToPath(new URL(`../verification/${profile}-viewer.png`,import.meta.url))});});
 }finally{await context.close();await browser.close();}
}
const browser=await chromium.launch({headless:true,executablePath});
try{
 await check('reduced motion remains static until deliberate inspection',async()=>{const page=await browser.newPage({reducedMotion:'reduce'});await page.goto(origin);await activate(page);assert(await page.getByRole('button',{name:'Follow page'}).isDisabled());const before=await page.evaluate(()=>window.__thesis.inspect().pose);await page.mouse.wheel(0,350);await page.waitForTimeout(200);assert.deepEqual(await page.evaluate(()=>window.__thesis.inspect().pose),before);await page.getByRole('button',{name:'Inspect',exact:true}).click();await setProgress(page,.75);assert.equal(await page.evaluate(()=>window.__thesis.inspect().mode),'inspect');await page.close();});
 await check('no JavaScript retains narrative, source images and model poster',async()=>{const page=await browser.newPage({javaScriptEnabled:false});await page.goto(origin);for(const img of await page.locator('img').all())await img.scrollIntoViewIfNeeded();await page.waitForTimeout(300);assert.equal(await page.locator('img').evaluateAll(a=>a.every(i=>i.complete&&i.naturalWidth>0)),true);assert((await page.locator('main').innerText()).includes('regression'));assert.equal(await page.locator('canvas').count(),0);await page.screenshot({path:fileURLToPath(new URL('../verification/no-js.png',import.meta.url))});await page.close();});
 for(const target of ['assembly.glb','studio-small.hdr'])await check('missing '+target+' preserves actual model capture',async()=>{const page=await browser.newPage();await page.route('**/'+target,r=>r.abort());await page.goto(origin);await page.getByRole('button',{name:'Explore the model',exact:true}).click();await page.getByText('The interactive view is unavailable.',{exact:false}).waitFor();assert(await page.locator('img[alt="Converted CAD assembly of the bending-active perforated metal surface"]').evaluate(i=>i.complete&&i.naturalWidth>0));await page.close();});
 await check('context loss has a readable fallback and bounded retry',async()=>{const page=await browser.newPage();await page.goto(origin);await activate(page);await page.evaluate(()=>window.__thesis.loseContext());await page.getByRole('button',{name:'Retry 3D'}).waitFor();assert.equal(await page.locator('canvas').count(),0);await page.getByRole('button',{name:'Retry 3D'}).click();await wait(page);await page.evaluate(()=>window.__thesis.loseContext());await page.waitForTimeout(150);assert.equal(await page.getByRole('button',{name:'Retry 3D'}).count(),0);await page.close();});
 for(const width of [390,768,1440])await check(width+'px reading and full-page layout',async()=>{const page=await browser.newPage({viewport:{width,height:1000}});await page.goto(origin);for(const img of await page.locator('img').all())await img.scrollIntoViewIfNeeded();await page.waitForTimeout(200);await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert(await page.locator('img').evaluateAll(a=>a.every(i=>i.complete&&i.naturalWidth>0)));await page.screenshot({path:fileURLToPath(new URL(`../verification/page-${width}.png`,import.meta.url)),fullPage:true});await page.close();});
 await check('local server rejects outside paths and nonlocal hosts',async()=>{assert.equal((await fetch(origin+'/../content/review.json')).status,404);assert.equal(await httpStatus({headers:{Host:'example.com'}}),403);assert.equal((await fetch(origin+'/',{method:'POST'})).status,403);const html=await(await fetch(origin+'/')).text();assert(!/[DE]:\\|portfolio-preparation|Window備份|asset-manifest/.test(html));});
}finally{await browser.close();}
await check('WebGL-disabled page uses the model poster',async()=>{const b=await chromium.launch({headless:true,executablePath,args:['--disable-webgl']});try{const p=await b.newPage();await p.goto(origin);await p.getByRole('button',{name:'Explore the model',exact:true}).click();await p.getByText('The interactive view is unavailable.',{exact:false}).waitFor();assert.equal(await p.locator('canvas').count(),0);assert(await p.locator('img[alt="Converted CAD assembly of the bending-active perforated metal surface"]').evaluate(i=>i.complete&&i.naturalWidth>0));}finally{await b.close();}});
await writeFile(new URL('../verification/browser.json',import.meta.url),JSON.stringify({verifiedAt:new Date().toISOString(),results,failures,limits:['Pixel 7 emulation; no physical device','Firefox not rerun; prior host launch failed','Software checks do not validate structural engineering or public release rights']},null,2)+'\n');
console.log(JSON.stringify({passed:results.length,failures},null,2));if(failures.length)process.exitCode=1;
