export const base = { roughness: .3, metalness: 1, coat: 0, exposure: 1, fill: .4, softness: 1, transmission: 1, thickness: 1.2, ior: 1.5, scatter: 0, restitution: .15, gravity: 9.81, count: 900, seed: 17, flow: .6, lens: 35, azimuth: 35, elevation: 24, projection: 'perspective' };
export const studies = [
  { id: 'materials', number: '01', family: 'FORM', title: 'Surface / substance', category: 'Materials', question: 'What makes the same form read as metal, ceramic or coated polymer?', a: 'Satin alloy', b: 'Coated ceramic', presets: [{roughness:.25,metalness:1,coat:0},{roughness:.48,metalness:0,coat:1}], controls: ['roughness','metalness','coat'], mechanism: 'Three MeshPhysicalMaterial: metalness, microfacet roughness and a separate clearcoat lobe. One original ribbed aperture, one fixed HDR and camera.', limit: 'A procedural surface study, not a measured material scan. No normal texture or fabricated material certification.', cost: 'Physical shading + one 1K PMREM environment; clearcoat adds fragment work.', reuse: 'scenes.jsx — Aperture / Surface', sources: ['three-physical','polyhaven','three-source'] },
  { id: 'lighting', number: '02', family: 'FORM', title: 'Light / edge', category: 'Light & shadow', question: 'How do fill and shadow filtering change the legibility of layers?', a: 'Hard key / deep fill', b: 'Soft filter / open fill', presets: [{metalness:.05,roughness:.55,fill:.02,softness:0,exposure:1},{metalness:.05,roughness:.55,fill:1.5,softness:4,exposure:1}], controls: ['fill','softness','exposure'], mechanism: 'Directional key casts an actual shadow map; a cool fill and warm rim reveal edges. ACES tone mapping and linear scene lighting.', limit: 'Softness is a VSM shadow-map filter radius, not a physical area-light penumbra. Environment reflection does not cast shadows. No GI.', cost: 'One 1024 px VSM shadow map plus its filter; no postprocessing.', reuse: 'scenes.jsx — LightRig', sources: ['three-shadows','three-color','polyhaven'] },
  { id: 'refraction', number: '03', family: 'FORM', title: 'Glass / thickness', category: 'Refraction', question: 'Does the background bend through a thick optical surface?', a: 'Clear solid', b: 'Rough thick solid', presets: [{roughness:.03,thickness:.5,ior:1.45},{roughness:.23,thickness:2.5,ior:1.9}], controls: ['roughness','thickness','ior'], mechanism: 'Physical transmission at opacity 1, volume thickness and index of refraction. Opaque stripes behind the object make the distortion visible.', limit: 'Raster transmission samples a screen-space opaque buffer. No nested transparent-object transport, ray-traced internal reflections or caustics. Thickness is a material parameter, not a solved exit surface.', cost: 'Transmission buffer and extra material sampling; single-stage A/B avoids duplicate buffers.', reuse: 'scenes.jsx — Optics', sources: ['three-physical','three-source','polyhaven'] },
  { id: 'scattering', number: '04', family: 'FORM', title: 'Diffuse / through-light', category: 'Diffusion & scattering', question: 'How does a backlit surface differ from ordinary diffuse reflection?', a: 'Lambert diffuse', b: 'Wrapped translucency', presets: [{scatter:0},{scatter:1}], controls: ['scatter'], mechanism: 'Original GLSL compares clamped N·L with wrapped diffuse and an exponential thickness-weighted backlight term. Light and normal are both in world space.', limit: 'A labeled surface-scattering approximation. No BSSRDF, multiple scattering, volumetric ray marching or true subsurface transport; it does not receive scene shadows.', cost: 'One shader pass; analytic thickness estimate and no textures.', reuse: 'scenes.jsx — ScatterSurface', sources: ['three-shader','pbrt-scattering'] },
  { id: 'physics', number: '05', family: 'MAKE', title: 'Drop / contact', category: 'Physics', question: 'How does restitution alter a set of colliding bodies in a tray?', a: 'Damped contact', b: 'Elastic contact', presets: [{restitution:.1,gravity:9.81},{restitution:.85,gravity:9.81}], controls: ['restitution','gravity'], mechanism: 'Rapier 0.19.3 WASM rigid bodies with gravity, sphere/sphere and sphere/tray contacts. Fixed 1/60 s integration, maximum five catch-up steps; time beyond that is dropped.', limit: 'Ideal rigid spheres and simplified colliders. No deformation, calibrated physical units, fracture, manufacturing or structural validation. A/B resets the same initial conditions.', cost: '12 dynamic spheres and 5 fixed colliders; world freed on close. Play is explicit.', reuse: 'physics.js — createDropWorld', sources: ['rapier','rapier-source'] },
  { id: 'particles', number: '06', family: 'SYSTEM', title: 'Field / circulation', category: 'Particles', question: 'Can a seeded particle field make flow around a form readable?', a: 'Axial drift', b: 'Helical circulation', presets: [{flow:0,count:900,seed:17},{flow:1,count:900,seed:17}], controls: ['flow','count','seed'], mechanism: 'Deterministic seeded initial positions; analytic time-dependent helical advection around a central mandrel, updated in CPU-owned position buffers with short analytic history trails. Fixed phase clock for reproducible reset.', limit: 'Illustrative kinematic field, not CFD, fluid particles, collision response or measured velocity. Count changes sample density, not physical mass.', cost: 'One Points draw call plus 120 analytic trail samples; 200–3000 particles. No per-frame React state.', reuse: 'particles.js — seedParticles / writeParticles', sources: ['three-points','r3f-performance'] },
  { id: 'camera', number: '07', family: 'SYSTEM', title: 'Lens / inspection', category: 'Camera', question: 'When does perspective communicate depth better than an orthographic survey?', a: 'Perspective / 35°', b: 'Orthographic survey', presets: [{projection:'perspective',lens:35},{projection:'orthographic',lens:35}], controls: ['lens','azimuth','elevation'], mechanism: 'Manual lens/pose controls and projection comparison. An explicitly played genuine Theatre inspection score reveals the rib relationships through the existing application adapter.', limit: 'Lens is vertical FOV, not a film focal length. Orthographic scale is matched at the target plane. Authored score takes exclusive camera ownership; a manual change pauses/releases it.', cost: 'A single active camera and one motion controller. Timeline and pose are inspectable.', reuse: 'scenes.jsx — CameraOwner; motion/theatre/runtime.js', sources: ['three-camera','theatre','r3f-performance'] },
];
export const controlSpecs = {
  roughness:['Roughness',0,1,.01], metalness:['Metalness',0,1,.01], coat:['Clearcoat',0,1,.01], exposure:['Exposure',.3,2,.05], fill:['Fill intensity',0,2,.05], softness:['Shadow filter radius',0,6,.25], thickness:['Optical thickness',0,3,.05], ior:['Index of refraction',1,2.3,.01], scatter:['Scatter approximation',0,1,.05], restitution:['Restitution',0,1,.05], gravity:['Gravity',0,15,.1], count:['Particle count',200,3000,100], seed:['Seed',1,100,1], flow:['Circulation',0,1,.05], lens:['Vertical FOV',20,65,1], azimuth:['Azimuth',-90,90,1], elevation:['Elevation',0,65,1],
};
export function preset(study, variant) { return {...base,...study.presets[variant === 'b' ? 1 : 0]}; }
