import React,{Suspense,lazy,useState,useRef,useEffect,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {studies,preset,controlSpecs} from './catalog';
import {readReview,parseReview,parseUIUX,storageKey} from './review';
import sourceRegister from '../catalog/archive-sources.json';
const LiveStage=lazy(()=>import('./scenes').then(module=>({default:module.Stage})));
const initial=readReview();
function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function getSelection(){const q=new URLSearchParams(location.search);return{study:studies.find(s=>s.id===q.get('study'))??null,variant:q.get('variant')==='b'?'b':'a'};}
class Boundary extends React.Component {state={error:false};static getDerivedStateFromError(){return{error:true};}componentDidCatch(){this.props.onFailure();}render(){return this.state.error?<p className="failure">The renderer stopped. Static images and review controls remain available.</p>:this.props.children;}}
function Desk(){
  const [selection,setSelection]=useState(getSelection),[review,setReview]=useState(initial.text),[notice,setNotice]=useState(initial.error??''),[filter,setFilter]=useState('All'),[live,setLive]=useState(false),[ready,setReady]=useState(false),[failed,setFailed]=useState(false),[playing,setPlaying]=useState(false),[epoch,setEpoch]=useState(0),[params,setParams]=useState(()=>preset(selection.study??studies[0],selection.variant)),[captures,setCaptures]=useState([]),[reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);
  const api=useRef(null),stageElement=useRef(null),diagnostic=useRef(null);const study=selection.study,variant=selection.variant;
  const stop=useCallback(()=>{setPlaying(false);},[]);
  const onReady=useCallback(()=>setReady(true),[]);
  const onFailure=useCallback(()=>{setFailed(true);setLive(false);setPlaying(false);setReady(false);},[]);
  const persist=next=>{setReview(next);try{localStorage.setItem(storageKey,JSON.stringify(next));}catch{setNotice('Choices remain in this tab. Storage is unavailable; export a backup.');}};
  function navigate(next,nextVariant='a',push=true){setPlaying(false);setLive(false);setReady(false);setFailed(false);setSelection({study:next,variant:nextVariant});setParams(preset(next??studies[0],nextVariant));setEpoch(x=>x+1);if(push)history.pushState({},'',next?`/bench/index.html?study=${next.id}&variant=${nextVariant}`:'/bench/index.html');}
  useEffect(()=>{const callback=()=>{const next=getSelection();navigate(next.study,next.variant,false);};window.addEventListener('popstate',callback);return()=>window.removeEventListener('popstate',callback);},[]);
  useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const callback=()=>{setReduced(media.matches);setPlaying(false);};media.addEventListener('change',callback);const visibility=()=>{if(document.hidden)setPlaying(false);};document.addEventListener('visibilitychange',visibility);return()=>{media.removeEventListener('change',callback);document.removeEventListener('visibilitychange',visibility);};},[]);
  useEffect(()=>{if(!live||!stageElement.current)return;const observer=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)setPlaying(false);});observer.observe(stageElement.current);return()=>observer.disconnect();},[live]);
  useEffect(()=>{const timer=setInterval(()=>{if(diagnostic.current&&api.current)diagnostic.current.textContent=JSON.stringify(api.current.inspect(),null,2);},350);return()=>clearInterval(timer);},[]);
  function applyVariant(next){stop();setReady(false);setSelection({study,variant:next});setParams(preset(study,next));setEpoch(x=>x+1);history.replaceState({},'',`/bench/index.html?study=${study.id}&variant=${next}`);}
  function edit(key,value){stop();setParams(p=>({...p,[key]:value}));}
  function toggleSave(){const found=review.saved.some(s=>s.id===study.id);persist({...review,saved:found?review.saved.filter(s=>s.id!==study.id):[...review.saved,{id:study.id,params,variant,savedAt:new Date().toISOString()}]});setNotice(found?'Removed from 3D Saved.':'Saved this study and its current parameters.');}
  async function importFile(event,isUIUX){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(file.size>1_000_000)throw new Error('Choose a JSON export smaller than 1 MB.');const text=await file.text();const value=JSON.parse(text);if(isUIUX){const basis=parseUIUX(value);const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));basis.fileSha256=Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');persist({...review,uiuxBasis:basis});}else persist(parseReview(value));setNotice(isUIUX?'UIUX export imported with file hash. This records supplied evidence, not independent identity verification.':'3D Saved and notes restored from export.');}catch(error){setNotice(`Import rejected: ${error.message}`);}}
  function capture(){if(!api.current)return;const captured=api.current.capture();setCaptures(current=>[...current.slice(-1),{...captured,id:study.id,title:study.title,variant,params:{...params},capturedAt:new Date().toISOString()}]);setNotice('Frozen image includes the actual pose, parameters and simulation time.');}
  const filtered=studies.filter(s=>filter==='All'||filter==='Saved'&&review.saved.some(v=>v.id===s.id)||s.family===filter);
  return <><a className="skip" href="#main">Skip to studies</a>
    <header><a className="brand" href="/bench/index.html" onClick={e=>{e.preventDefault();navigate(null);}}>FORM <i>/</i> SYSTEM <i>/</i> MAKE</a><span className="edition">ARCHIVE · PARAMETER BENCH 01</span><a href="#review">Saved {review.saved.length.toString().padStart(2,'0')} ↗</a></header>
    <main id="main">
      {!study?<section className="intro"><p className="eyebrow">LOCAL RESEARCH / ORIGINAL GEOMETRY / 07 STUDIES</p><h1>Material.<br/>Light. <em>Behaviour.</em></h1><div className="intro-bottom"><p>Seven controlled experiments in how a form is seen, moves and responds. Compare the stills. Open one stage. Keep what matters.</p><span>01 — 04 / FORM<br/>05 / MAKE<br/>06 — 07 / SYSTEM</span></div></section>:<section className="study" aria-labelledby="study-title"><div className="breadcrumbs"><a href="/bench/index.html" onClick={e=>{e.preventDefault();navigate(null);}}>← All studies</a><span>{study.family} / {study.category}</span><span>{study.number} / 07</span></div><h1 id="study-title">{study.title}</h1><p className="question">{study.question}</p><div className="workbench"><div className="stage-column"><div className="stage" ref={stageElement}>
        {live?<Boundary key={epoch} onFailure={onFailure}><Suspense fallback={<div className="loading">Preparing the local renderer…</div>}><LiveStage {...{study,params,playing,setPlaying,epoch,api,onReady,onFailure}}/></Suspense></Boundary>:<img className="stage-poster" src={`/assets/posters/${study.id}-${variant}.png`} alt={`${study.title}, ${variant==='a'?study.a:study.b}; static captured study`}/>}
        <span className="stage-badge">{live?(ready?'LIVE / '+(playing?'PLAYING':'AT REST'):'LOADING'):'CAPTURED STILL'} · {variant.toUpperCase()}</span></div>
        <div className="transport">{!live?<button className="primary" onClick={()=>{setFailed(false);setReady(false);setLive(true);}}>Open live stage</button>:<><button onClick={()=>{setLive(false);stop();setReady(false);}}>Close live stage</button>{['physics','particles','camera'].includes(study.id)&&<button disabled={!ready} onClick={()=>setPlaying(v=>!v)}>{playing?'Pause':'Play'}</button>}{['physics','particles'].includes(study.id)&&<button disabled={!ready||playing} onClick={()=>api.current?.step()}>Step 1/60 s</button>}<button disabled={!ready} onClick={capture}>Freeze comparison</button></>}<button onClick={()=>{stop();setReady(false);setParams(preset(study,variant));setEpoch(x=>x+1);}}>Reset</button></div>
        {failed&&<p role="alert">WebGL could not continue. The captured still is available; reopen to retry.</p>}{reduced&&<p className="motion-note">Reduced motion is enabled. Nothing plays automatically; Play is optional.</p>}
        <p className="caption">Original aperture / local studio illumination / ACES tone mapping. The poster records its preset; edited parameters apply in the live stage.</p>
      </div><aside className="controls"><p className="eyebrow">CONTROLLED COMPARISON</p><div className="variants"><button aria-pressed={variant==='a'} onClick={()=>applyVariant('a')}><b>A</b> {study.a}</button><button aria-pressed={variant==='b'} onClick={()=>applyVariant('b')}><b>B</b> {study.b}</button></div>
        {study.controls.map(key=><label className="slider" key={key}><span>{controlSpecs[key][0]}<output>{params[key]}</output></span><input type="range" min={controlSpecs[key][1]} max={controlSpecs[key][2]} step={controlSpecs[key][3]} value={params[key]} onChange={e=>edit(key,Number(e.target.value))}/></label>)}
        {study.id==='camera'&&<label className="select">Projection<select value={params.projection} onChange={e=>edit('projection',e.target.value)}><option value="perspective">Perspective</option><option value="orthographic">Orthographic</option></select></label>}
        <button className="save" aria-pressed={review.saved.some(s=>s.id===study.id)} onClick={toggleSave}>{review.saved.some(s=>s.id===study.id)?'✓ Saved':'＋ Save this study'}</button><label className="notes">Review notes<textarea value={review.notes[study.id]??''} maxLength={5000} placeholder="What should carry forward?" onChange={e=>persist({...review,notes:{...review.notes,[study.id]:e.target.value}})}/></label>
        {review.saved.some(s=>s.id===study.id)&&<button onClick={()=>{const saved=review.saved.find(s=>s.id===study.id);stop();setParams(saved.params);setSelection({study,variant:saved.variant});setEpoch(x=>x+1);setNotice('Restored the parameters recorded when saved.');}}>Restore saved parameters</button>}
      </aside></div><div className="study-notes"><div><h2>What is running</h2><p>{study.mechanism}</p></div><div><h2>Where it stops</h2><p>{study.limit}</p></div><div><h2>Cost & reuse</h2><p>{study.cost}</p><a href={`/samples/${study.reuse.split(' — ')[0]}`} target="_blank" rel="noreferrer">Reusable source ↗</a></div></div><details><summary>Sources, licenses & live diagnostics</summary><p><a href="/catalog/archive-sources.json">Primary source register</a> · <a href="/catalog/assets.manifest.json">Local assets + SHA-256</a> · <a href="/licenses/CC0-1.0.txt">HDR license</a></p><ul>{study.sources.map(id=>{const source=sourceRegister.sources.find(item=>item.id===id);return <li key={id}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> — {source.application}</li>;})}</ul><p>UIUX preference basis: {review.uiuxBasis?'supplied export recorded below':'not captured; this is a candidate interpretation of the written brief'}.</p><pre ref={diagnostic}>Open the live stage for actual camera, frame and memory readings.</pre></details></section>}
      {captures.length>0&&<section className="frozen"><div className="section-top"><h2>Frozen comparison</h2><button onClick={()=>setCaptures([])}>Clear captures</button></div><div className="capture-grid">{captures.map((capture,i)=><figure key={i}><img src={capture.image} alt={`Frozen ${capture.title} ${capture.variant.toUpperCase()}`}/><figcaption>{capture.title} · {capture.variant.toUpperCase()} · {capture.state.time.toFixed(2)} s</figcaption><details><summary>Captured state</summary><pre>{JSON.stringify({...capture,image:undefined},null,2)}</pre></details><button onClick={()=>download(`3d-${capture.id}-${capture.variant}-capture.json`,capture)}>Export image + state</button></figure>)}</div></section>}
      <section id="studies"><div className="section-top"><h2>Study index <small>/ 07</small></h2><nav aria-label="Study filters">{['All','FORM','SYSTEM','MAKE','Saved'].map(label=><button key={label} aria-pressed={filter===label} onClick={()=>setFilter(label)}>{label}</button>)}</nav></div><div className="contact-sheet">{filtered.map(s=><article className="card" key={s.id}><a href={`/bench/index.html?study=${s.id}&variant=a`} onClick={e=>{e.preventDefault();navigate(s);window.scrollTo(0,0);}}><div className="card-meta"><span>{s.number} / {s.category}</span><span>{s.family}</span></div><div className="poster-pair"><img src={`/assets/posters/${s.id}-a.png`} alt={`A: ${s.a}`} loading="lazy"/><img src={`/assets/posters/${s.id}-b.png`} alt={`B: ${s.b}`} loading="lazy"/><span>A / B</span></div><div className="card-title"><h3>{s.title}</h3><span>↗</span></div><p>{s.question}</p><div className="card-labels"><span>A — {s.a}</span><span>B — {s.b}</span></div></a>{review.saved.some(v=>v.id===s.id)&&<span className="saved-marker">✓ Saved</span>}</article>)}</div>{!filtered.length&&<p>No studies saved yet. Open a study to record a preference.</p>}</section>
      <section id="review" className="review"><p className="eyebrow">PREFERENCE RECORD / LOCAL ONLY</p><h2>Keep the evidence.</h2><p>3D Saved includes parameters and notes. Imported UIUX choices stay separate. Opening a study does not record approval.</p><div className="actions"><button onClick={()=>download('3d-artist-review.json',{...review,exportedAt:new Date().toISOString(),origin:location.origin,purpose:'Owner discussion; no publication approval'})}>Export 3D Saved + notes</button><label className="file-button">Import 3D review<input type="file" accept=".json,application/json" onChange={e=>importFile(e,false)}/></label><button onClick={()=>window.print()}>Print contact sheet</button></div><div className="basis"><h3>UIUX preference basis</h3><p>{review.uiuxBasis?`${review.uiuxBasis.saved.length} supplied choices · exported ${review.uiuxBasis.exportedAt}`:'Not captured. These studies follow the written cinematic engineering brief; no Saved IDs have been guessed.'}</p><label className="file-button">Import real UIUX export<input type="file" accept=".json,application/json" onChange={e=>importFile(e,true)}/></label><a href="http://127.0.0.1:4175/" target="_blank" rel="noreferrer">Open original UIUX desk ↗</a>{review.uiuxBasis&&<details><summary>Inspect imported evidence</summary><p>Imported files are supplied evidence. Unknown historical IDs remain here for review; old Saves do not prove review of later treatments.</p><pre>{JSON.stringify(review.uiuxBasis,null,2)}</pre></details>}</div>
      </section><p role="status" className="notice">{notice}</p>
    </main><footer><span>3D ARTIST / ORIGINAL LOCAL PROPOSALS</span><span>Research artifact · production adoption pending</span><a href="/catalog/archive-studies.json">Catalog JSON ↗</a></footer>
  </>;
}
createRoot(document.getElementById('root')).render(<Desk/>);
