import { node, range, control, scaffold } from './helpers.js';
import { feedbackControls } from '../applied-feedback/controls.js';
export default function ascii(root, material, context) {
  const shell = scaffold(root, material); const { stage, controls, status } = shell; const stack = node('div', undefined, { class: 'ascii-stack' }); const art = node('pre', undefined, { class: 'ascii-art', 'aria-hidden': 'true' }); const layers = Array.from({ length: 3 }, (_, i) => { const layer = node('div', undefined, { class: 'ascii-slice', 'data-band': i, 'aria-hidden': 'true' }); layer.append(node('pre')); return layer; }); stack.append(art, ...layers); stage.append(stack);
  let phase = 0; let columns = 44; let band = -1;
  const feedback = feedbackControls(shell, context, { separation: .7 }, (value, spatial) => { stack.dataset.mode = spatial ? 'spatial' : 'baseline'; layers.forEach((layer, i) => { layer.style.transform = `translate3d(${(i - 1) * value.separation * 14}px,${(1 - i) * value.separation * 24}px,${i * value.separation * 26}px) rotateX(24deg) rotateY(-10deg)`; }); });
  const selection = node('div', undefined, { class: 'part-selection', role: 'group', 'aria-label': 'Height range' }); const selectors = ['All heights', 'Low', 'Middle', 'High'].map((label, i) => { const b = control(selection, label, () => { band = i - 1; render(); }); return b; }); controls.before(selection);
  const render = () => { const ramp = ' .:-=+*#%@'; const rows = Math.round(columns * .42); const values = Array.from({ length: rows }, (_, y) => Array.from({ length: columns }, (_, x) => (Math.sin(x / columns * Math.PI * 3 + phase) * Math.cos(y / rows * Math.PI * 2) + 1) / 2)); const inBand = (value, range) => Math.min(2, Math.floor(value * 3)) === range; const text = range => values.map(row => row.map(value => range < 0 || inBand(value, range) ? ramp[Math.min(9, Math.floor(value * 10))] : ' ').join('')).join('\n'); art.textContent = text(band); const fontSize = `${Math.min(12, stage.clientWidth * .72 / (columns * .7))}px`; art.style.fontSize = fontSize; stack.style.minHeight = `${Math.max(260, rows * parseFloat(fontSize) * 1.25 + 100)}px`; layers.forEach((layer, i) => { layer.hidden = band >= 0 && band !== i; layer.firstElementChild.textContent = text(i); layer.firstElementChild.style.fontSize = fontSize; }); selectors.forEach((b, i) => b.setAttribute('aria-pressed', String(i - 1 === band))); stage.dataset.band = String(band); status.textContent = `Generated sinusoidal height field: ${columns} × ${rows} cells; phase ${phase.toFixed(2)} radians. ${band < 0 ? 'All heights' : ['Low', 'Middle', 'High'][band]} shown. Character density encodes height.`; };
  const separation = range(controls, 'Slice separation', 0, 1, .1, .7, value => feedback.to({ separation: value }));
  const phaseControl = range(controls, 'Phase / radians', 0, 6.28, .1, phase, value => { phase = value; render(); }); const density = range(controls, 'Columns', 28, 64, 4, columns, value => { columns = value; render(); });
  control(controls, 'Reset', () => { phase = 0; columns = 44; band = -1; phaseControl.input.value = '0'; phaseControl.output.textContent = '0'; density.input.value = '44'; density.output.textContent = '44'; separation.input.value = '.7'; separation.output.textContent = '0.7'; feedback.snap({ separation: .7 }); render(); });
  let resizeFrame = 0; let lastWidth = stage.clientWidth;
  const resize = new ResizeObserver(() => { const width = stage.clientWidth; if (width === lastWidth) return; lastWidth = width; cancelAnimationFrame(resizeFrame); resizeFrame = requestAnimationFrame(render); });
  resize.observe(stage); render(); return () => { feedback.destroy(); resize.disconnect(); cancelAnimationFrame(resizeFrame); };
}
