import { node, range, scaffold, control } from './helpers.js';
import { feedbackControls, pressFeedback } from '../applied-feedback/controls.js';
export function font(root, material, context) {
  const parts = scaffold(root, material); const { stage, controls, status } = parts;
  const display = node('div', 'Form becomes a system.', { class: 'font-display', 'aria-label': 'Editable type specimen' }); display.style.fontFamily = `'${material.cssFamily}'`;
  const paragraph = node('p', 'A geometric rule can be read as a drawing, an interaction or a sequence of parts. Use the same words across font comparisons, then inspect the distinctions in rhythm, spacing and small numerals.', { class: 'font-paragraph' }); paragraph.style.fontFamily = `'${material.cssFamily}'`; stage.append(display, paragraph);
  const label = node('label', 'Specimen text'); const text = node('input', undefined, { type: 'text', value: display.textContent }); label.append(text); controls.append(label);
  let words = []; let lifted = false;
  const feedback = feedbackControls(parts, context, { lift: 0 }, (value, spatial) => { words.forEach((word, i) => { const depth = spatial ? value.lift : 0; word.style.transform = `translate3d(0,${-depth * (i % 2 ? 7 : 2)}px,${depth * (15 + i % 3 * 12)}px) rotateX(${depth * (i % 2 ? -12 : 8)}deg) rotateY(${depth * (i % 3 - 1) * 9}deg)`; }); stage.dataset.lift = value.lift.toFixed(3); });
  const renderWords = () => { words = []; display.replaceChildren(...text.value.split(/(\s+)/).map(value => { if (/^\s+$/.test(value)) return document.createTextNode(value); const word = node('span', value, { class: 'type-word' }); words.push(word); return word; })); feedback.snap(); };
  text.addEventListener('input', renderWords);
  const lift = control(controls, 'Lift heading', () => { lifted = !lifted; lift.setAttribute('aria-pressed', String(lifted)); feedback.to({ lift: lifted ? 1 : 0 }); }); lift.setAttribute('aria-pressed', 'false'); renderWords();
  range(controls, 'Size / px', 24, 72, 1, 48, value => { display.style.fontSize = `${value}px`; }); display.style.fontSize = '48px';
  if (!material.fixedWeight) range(controls, 'Weight', material.cssFamily === 'Space Grotesk' ? 300 : 100, material.cssFamily === 'Inter' ? 900 : 700, 100, 400, value => { display.style.fontWeight = value; });
  document.fonts.load(`16px "${material.cssFamily}"`).then(faces => { status.textContent = faces.length ? `Local font loaded: ${material.family}` : 'Font unavailable; system fallback shown.'; }).catch(() => { status.textContent = 'Font unavailable; system fallback shown.'; });
  return () => feedback.destroy();
}
export function icons(root, material, context) {
  const parts = scaffold(root, material); const { stage, controls, status } = parts; const grid = node('div', undefined, { class: 'specimen-icons' });
  const rigs = [], buttons = []; let selected = -1; const initial = {};
  const images = material.assets.filter(file => file.endsWith('.svg')).map((file, i) => { const name = file.split('/').at(-1).replace('.svg', ''); const cell = node('div', undefined, { class: 'icon-cell' }); const button = node('button', undefined, { class: 'icon-select', 'aria-label': `Inspect ${name}`, 'aria-pressed': 'false' }); const rig = node('span', undefined, { class: 'icon-rig' }); const image = node('span', undefined, { class: 'masked-icon', 'aria-hidden': 'true' }); image.style.maskImage = `url('/${file}')`; rig.append(image); button.append(rig); cell.append(button, node('a', name, { href: `/${file}`, download: '' })); grid.append(cell); rigs.push(rig); buttons.push(button); initial[`lift${i}`] = 0; initial[`press${i}`] = 0; return image; }); stage.append(grid);
  const feedback = feedbackControls(parts, context, initial, (value, spatial) => { rigs.forEach((rig, i) => { const lift = spatial ? value[`lift${i}`] : 0, press = spatial ? value[`press${i}`] : 0; rig.style.transform = `translateZ(${lift * 25 - press * 8}px) rotateX(${lift * -12 + press * 7}deg) rotateY(${lift * 9}deg)`; }); });
  buttons.forEach((button, i) => { button.addEventListener('click', () => { selected = selected === i ? -1 : i; const values = {}; buttons.forEach((b, index) => { b.setAttribute('aria-pressed', String(index === selected)); values[`lift${index}`] = index === selected ? 1 : 0; }); feedback.to(values); stage.dataset.selected = String(selected); status.textContent = selected < 0 ? 'Glyph returned to its resting plane.' : `Inspecting ${material.assets.filter(file => file.endsWith('.svg'))[i].split('/').at(-1)}. Download keeps the original SVG bytes.`; }); pressFeedback(button, press => feedback.to({ [`press${i}`]: press })); });
  range(controls, 'Size / px', 20, 64, 2, 32, value => { images.forEach(image => { image.style.width = `${value}px`; image.style.height = `${value}px`; }); }); status.textContent = '12 actual local SVGs. Select a label to download its original file.';
  return () => feedback.destroy();
}
export function glyphs(root, material, context) {
  const parts = scaffold(root, material); const { stage, controls, status } = parts; const group = node('div', undefined, { class: 'specimen-glyphs' }); const rigs = [], buttons = [];
  const images = material.assets.map((file, index) => { const figure = node('figure'); const image = node('img', undefined, { src: `/${file}`, alt: '' }); const button = node('button', undefined, { class: 'glyph-button', 'aria-label': `Inspect ${['FORM', 'SYSTEM', 'MAKE'][index]}`, 'aria-pressed': 'false' }); const rig = node('span', undefined, { class: 'glyph-rig' }); rig.append(image); button.append(rig); figure.append(button, node('figcaption', ['FORM', 'SYSTEM', 'MAKE'][index])); group.append(figure); rigs.push(rig); buttons.push(button); return image; }); stage.append(group);
  const feedback = feedbackControls(parts, context, { form: 0, system: 0, make: 0 }, (value, spatial) => { rigs.forEach((rig, i) => { const amount = spatial ? value[['form', 'system', 'make'][i]] : 0; rig.style.transform = `translateZ(${amount * 35}px) rotateX(${amount * [18, -12, 0][i]}deg) rotateY(${amount * [-18, 16, 28][i]}deg)`; }); });
  buttons.forEach((button, i) => button.addEventListener('click', () => { const open = button.getAttribute('aria-pressed') !== 'true'; buttons.forEach(b => b.setAttribute('aria-pressed', String(b === button && open))); feedback.to(Object.fromEntries(['form', 'system', 'make'].map((key, index) => [key, index === i && open ? 1 : 0]))); status.textContent = open ? ['FORM: inspect the section and its curvature.', 'SYSTEM: inspect connections between parts.', 'MAKE: inspect the mating relationship.'][i] : 'All marks returned to their reading plane.'; }));
  range(controls, 'Mark size / px', 36, 100, 2, 80, value => { images.forEach(image => { image.style.width = `${value}px`; }); }); status.textContent = 'Original marks, with readable labels. Themes, not skill scores.';
  return () => feedback.destroy();
}
export function palette(root, material, context) {
  const parts = scaffold(root, material); const { stage, controls, status } = parts;
  const colors = [{ label: 'Primary text', text: '#f2f0ea' }, { label: 'Secondary text', text: '#a7adb5' }, { label: 'Interaction accent', text: '#ff7a45' }, { label: 'Accent button', text: '#0b0d10', background: '#ff7a45' }];
  const lum = hex => { const rgb = hex.match(/[a-f0-9]{2}/gi).map(value => parseInt(value, 16) / 255).map(value => value <= .04045 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4); return rgb[0] * .2126 + rgb[1] * .7152 + rgb[2] * .0722; };
  let background = '#0b0d10'; const grid = node('div', undefined, { class: 'palette-grid' }); stage.append(grid);
  const feedback = feedbackControls(parts, context, { open: 0 }, (value, spatial) => { grid.querySelectorAll('.palette-swatch').forEach((swatch, i) => { const amount = spatial ? value.open : 0; swatch.style.transform = `translateZ(${amount * 18}px) rotateX(${amount * -22}deg) rotateY(${amount * (i % 2 ? 9 : -9)}deg)`; }); });
  let open = false; const separate = control(controls, 'Separate color plates', () => { open = !open; separate.setAttribute('aria-pressed', String(open)); feedback.to({ open: Number(open) }); }); separate.setAttribute('aria-pressed', 'false');
  const update = () => { grid.replaceChildren(...colors.map(color => { const bg = color.background ?? background; const ratio = (Math.max(lum(color.text), lum(bg)) + .05) / (Math.min(lum(color.text), lum(bg)) + .05); const chip = node('div', undefined, { class: 'palette-chip' }); chip.style.background = bg; chip.style.color = color.text; const swatch = node('div', undefined, { class: 'palette-swatch', 'aria-hidden': 'true' }); swatch.style.background = color.text; chip.append(swatch, node('strong', color.label), node('p', `${color.text} / ${bg}`), node('p', `${ratio.toFixed(2)}:1 text contrast`)); return chip; })); feedback.snap(); status.textContent = `Measured color pairings on ${background}. This is a pairing check, not a full accessibility audit.`; };
  control(controls, 'Base background', () => { background = '#0b0d10'; update(); }); control(controls, 'Raised surface', () => { background = '#14181d'; update(); }); update();
  return () => feedback.destroy();
}
